export const GET_WEATHER = "GET_WEATHER";
export const WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const WEATHER_FAILURE = "WEATHER_FAILURE";

export const GET_FORECAST = "GET_FORECAST";
export const FORECAST_SUCCESS = "FORECAST_SUCCESS";
export const FORECAST_FAILURE = "FORECAST_FAILURE";
